### ISSUE TITLE
Responsive typography

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/robertocarroll.github.com#15]
### Responsive typography
-  match up inuit base font size with the size in html
- http://typecast.com/blog/jordan-moore-on-mobile-first-type-layout
- http://typecast.com/blog/a-more-modern-scale-for-web-typography
- https://ia.net/know-how/responsive-typography-the-basics
- https://github.com/inuitcss/getting-started

### Rems, `font-size`, and scaling
(Mine doesn't quite work like this but I'm keeping it for reference.)

Poole is built almost entirely with `rem`s (instead of pixels). `rem`s are like `em`s, but instead of building on the immediate parent's `font-size`, they build on the root element, `<html>`.

By default, we use the following:

```css
html {
  font-size: 16px;
  line-height: 1.5;
}
@media (min-width: 38em) {
  html {
    font-size: 20px;
  }
}

```

To easily scale your site's typography and components, simply customize the base `font-size`s here.
